#ifndef __CENTERSERVER_WINDOWSUSERMESSAGE_H__
#define __CENTERSERVER_WINDOWSUSERMESSAGE_H__

enum
{
    WM_UPDATEGAMESERVERINFO = WM_USER+1001,
    WM_OUTPUTINFO,
};

#endif // __CENTERSERVER_WINDOWSUSERMESSAGE_H__
