//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WorldEditor.rc
//
#define IDCANCEL2                       3
#define IDB_MAP_MODELS_TO_POS           3
#define IDB_MAP_MODELS_EXPORT           3
#define IDOK2                           4
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_WorldEditTYPE               129
#define IDB_BITMAP_ICONS                130
#define IDD_DLG_NEWWORLD                131
#define IDR_WORLD_EXPLORER              136
#define IDD_DLG_NEW_WTD                 138
#define IDR_TB_EDIT                     139
#define IDR_TOOLS_HEAD                  151
#define IDD_DLG_TERRAIN                 153
#define IDR_TOOLBAR_ATOM                154
#define IDB_BITMAP_SIZELIST             156
#define IDB_BITMAP_TERRAIN              157
#define IDD_DLG_MODEL                   158
#define IDD_DLG_LAYER                   159
#define IDD_DLG_DOODADS                 161
#define IDD_DLG_LIQUID                  162
#define IDD_DLG_WORLD                   163
#define IDD_DLG_ENV                     164
#define IDD_DLG_ADDTILE                 166
#define IDD_DIALOG1                     167
#define IDD_DLG_LIGHT                   167
#define IDR_LIST_MENU_POPUP             168
#define IDR_LIST_TILE_MENU              170
#define IDD_DLG_RELACE_TILE_TEXTURE     171
#define IDD_DLG_SNAPMINIMAP             172
#define IDD_DLG_SERVERMAP               173
#define IDD_DLG_FOG                     174
#define IDD_DLG_DOODADS_NEWLEVEL        175
#define IDB_BITMAP_WORLDTREEICON        177
#define IDD_REACHABLEMAP                178
#define IDD_DLG_TRANSPORT               179
#define IDD_DLG_MERGE_WTD               180
#define IDD_DLG_MONSTERQUAD             182
#define IDD_DLG_SPLIT_WTD               183
#define IDD_LIGHTMAP_PROCESS            184
#define IDD_LIGHTMAP                    185
#define IDD_DLG_SKYBOXBLOOM             186
#define IDD_DLG_ZONE                    187
#define IDD_DLG_FLYROUTE                188
#define IDD_DLG_Click2Add               189
#define IDD_DIALOG_ATTRIBUTE            190
#define IDD_DIALOG_NPC                  191
#define IDD_DIALOG2                     194
#define IDD_NPCEDIT_DIALOG              194
#define IDD_UPDATEPOS                   197
#define IDD_DIALOG3                     198
#define IDD_NPCSTRING                   198
#define IDD_DIALOG_SETMESH              200
#define IDD_DIALOG_ColiCheckResult      200
#define IDD_LIGHTMAP_MESH_PROCESS       201
#define IDD_DLG_LOCATE                  202
#define IDR_MENU1                       203
#define IDR_MENU_model_transform        203
#define IDD_DIALOG_CONTRAST             204
#define IDD_DIALOG_STATIC_LIGHT         205
#define IDD_DIALOG_BLOOM                206
#define IDD_DIALOG4                     207
#define IDD_CAMERA_FOLLOW               207
#define IDD_MAP_MODELS                  208
#define IDC_EDT_FILENAME                1006
#define IDC_EDT_WORLD_PATH              1006
#define IDC_EDT_WORLD_NAME              1007
#define IDC_EDT_NEWWTD_X                1009
#define IDC_EDT_NEWWTD_NAME             1009
#define IDC_EDT_NEWWTD_Y                1010
#define IDC_EDT_NEWWTD_TEXTURE          1011
#define IDC_EDT_NEWWTD_HEIGHTMAP        1012
#define IDC_EDT_NEWWTD_WIDTH            1013
#define IDC_EDT_NEWWTD_ROW              1013
#define IDC_EDT_MERGEWTD_DOWNRIGHT      1013
#define IDC_EDIT_NEWWTD_HEIGHT          1014
#define IDC_RD_NEWWTD_HEIGHTMAP         1015
#define IDC_EDT_NEWWTD_HEIGHT           1015
#define IDC_EDT_NEWWTD_COLUMN           1015
#define IDC_RD_NEWWTD_NOHEIGHTMAP       1016
#define IDC_CK_NEWWTD_HEIGHTMAP         1018
#define IDC_EDT_NEWWTD_HEIGHTMAP_UNIT   1019
#define IDC_SLIDER_BRUSH_ALPHA          1024
#define IDC_BRUSH_SET                   1026
#define IDC_BRUSH_ADD                   1027
#define IDC_BRUSH_DELTA                 1028
#define IDC_BTN_TEXTURE_ADD             1030
#define IDC_BTN_TEXTURE_REMOVE          1031
#define IDC_PREVIEW_LAYER_0             1035
#define IDC_PREVIEW_LAYER_1             1036
#define IDC_PREVIEW_LAYER_2             1037
#define IDC_PREVIEW_LAYER_3             1038
#define IDC_BTN_DEL_LAYER_0             1040
#define IDC_BTN_DEL_LAYER_1             1041
#define IDC_BTN_DEL_LAYER_2             1042
#define IDC_BTN_DEL_LAYER_3             1043
#define IDC_BTN_GET_LAYER_0             1050
#define IDC_BTN_GET_LAYER_1             1051
#define IDC_BTN_GET_LAYER_2             1052
#define IDC_BTN_GET_LAYER_3             1053
#define IDC_BTN_SET_LAYER_0             1054
#define IDC_BTN_SET_LAYER_1             1055
#define IDC_BTN_SET_LAYER_2             1056
#define IDC_BTN_SET_LAYER_3             1057
#define IDC_BTN_UP_LAYER_0              1058
#define IDC_BTN_UP_LAYER_1              1059
#define IDC_BTN_UP_LAYER_2              1060
#define IDC_BTN_DOWN_LAYER_1            1061
#define IDC_BTN_DOWN_LAYER_2            1062
#define IDC_BTN_DOWN_LAYER_3            1063
#define IDC_COMBO_LAYER_MODE            1064
#define IDC_BRUSH_SIZE1                 1065
#define IDC_BTN_SET_LAYER_4             1065
#define IDC_BTN_REFRESH_TEXTURE         1065
#define IDC_BRUSH_SIZE2                 1066
#define IDC_BRUSH_SIZE3                 1067
#define IDC_BRUSH_SIZE4                 1068
#define IDC_BRUSH_SIZE5                 1069
#define IDC_BTN_ADDTILE                 1070
#define IDC_BTN_MODEL_ADD               1071
#define IDC_BTN_MODEL_DEL               1072
#define IDC_BTN_MODEL_CHANGE            1072
#define IDC_BTN_DELTILE                 1073
#define IDC_BTN_NEWTILE                 1074
#define IDC_STATIC_SIZE                 1075
#define IDC_BTN_REFRESH                 1075
#define IDC_STATIC_SHAPE                1076
#define IDC_BTN_NEWFOLDER               1076
#define IDC_BRUSH_SHAPE_RECT            1077
#define IDC_BRUSH_SHAPE_CIRCLE          1078
#define IDC_HEIGHT_UPDOWN               1079
#define IDC_HEIGHT_SMOOTH               1080
#define IDC_HEIGHT_PLANE                1081
#define IDC_HEIGHT_EQUAL                1082
#define IDC_CHECK_APPLYHEIGHT           1085
#define IDC_COMBO1                      1085
#define IDC_CMB_CLASS                   1085
#define IDC_CMB_DOODADS                 1085
#define IDC_CMB_LIGHT                   1085
#define IDC_COMBO_TYPE                  1085
#define IDC_COMBO_VESTTYPE              1085
#define IDC_COMBO_LIGHTMAP_RESOLUTION   1085
#define IDC_COMRTYPE                    1085
#define IDC_COMBO2                      1086
#define IDC_CMB_SUBCLASS                1086
#define IDC_COMBO_OPTMODE               1086
#define IDC_HEIGHT_SHAPE2               1086
#define IDC_CMB_FOG                     1086
#define IDC_COMBO_STATUS                1086
#define IDC_COMETYPE                    1086
#define IDC_LIST1                       1087
#define IDC_LIST_MODEL                  1087
#define IDC_LIST_PICKED_MODEL           1087
#define IDC_LIST_FLYROUTE               1087
#define IDC_NPCMENU_LIST                1087
#define IDC_LIST_AUTOTALK               1087
#define IDC_LIST_MAP_MODEL              1087
#define IDC_EDIT_ALPHA                  1088
#define IDC_LIST_PICKRESULT             1088
#define IDC_LIST_TALK                   1088
#define IDC_SPIN_ALPHA                  1089
#define IDC_COMBO3                      1089
#define IDC_COMBO_LAYER_BRUSH           1090
#define IDC_COMBO_LAYER_BRUSH2          1091
#define IDC_COMBO_LAYER_FOLDER          1091
#define IDC_COMBO_LAYER_TEXTURE         1091
#define IDC_PREVIEW_LAYER               1092
#define IDC_CHK_LOCKLAYER               1093
#define IDC_EDIT_FLOW                   1094
#define IDC_EDT_OFFSET_POS_X            1095
#define IDC_SPIN_FLOW                   1095
#define IDC_EDT_OFFSET_POS_Y            1096
#define IDC_TREE1                       1097
#define IDC_TREE_WORLD                  1097
#define IDC_EDT_OFFSET_POS_Z            1097
#define IDC_TREE_STATUS                 1097
#define IDC_NPCLIST                     1097
#define IDC_STATIC_NAME_PROMPT          1098
#define IDC_EDT_OFFSET_ROT_X            1098
#define IDC_EDT_OFFSET_ROT_Y            1099
#define IDC_EDT_OFFSET_ROT_Z            1100
#define IDC_EDT_OFFSET_SCL_X            1101
#define IDC_EDT_OFFSET_SCL_XYZ          1101
#define IDC_EDT_OFFSET_SCL_Y            1102
#define IDC_TREE_MODEL                  1102
#define IDC_EDT_OFFSET_SCL_Z            1103
#define IDC_EDT_WORLD_X                 1104
#define IDC_EDT_WORLD_Y                 1105
#define IDC_EDT_WORLD_Z                 1106
#define IDC_CHK_PICKOBJ                 1107
#define IDC_CHK_LOCK_PARAM_ROT          1108
#define IDC_EDT_TRANSPORT_X             1108
#define IDC_CHK_LOCK_PARAM_OFF          1109
#define IDC_EDT_TRANSPORT_Y             1109
#define IDC_CHK_LOCK_PARAM_SCL          1110
#define IDC_EDT_TRANSPORT_X_SCALE       1110
#define IDC_EDT_FLYROUTE_Z              1110
#define IDC_BTN_RESET                   1111
#define IDC_EDT_TARGET_X                1111
#define IDC_BTN_RESET2                  1112
#define IDC_BTN_SET                     1112
#define IDC_CHK_LOCK_PARAM              1113
#define IDC_EDT_WORLD_Y_SPIN            1114
#define IDC_EDIT_HEIGHTSTEP             1114
#define IDC_EDIT_HEIGHTSTRENGTH         1114
#define IDC_EDT_WORLD_X_SPIN            1115
#define IDC_EDIT_HEIGHTSPEED            1115
#define IDC_EDT_OFFSET_POS_X_SPIN       1116
#define IDC_SPIN_HEIGHTSTEP             1116
#define IDC_EDT_OFFSET_POS_Y_SPIN       1117
#define IDC_TILE_NAVIGATION             1117
#define IDC_EDT_OFFSET_POS_Z_SPIN       1118
#define IDC_TILE_PROMPT                 1118
#define IDC_EDT_OFFSET_ROT_Y_SPIN       1119
#define IDC_EDT_OFFSET_ROT_X_SPIN       1120
#define IDC_CHK_SHOWGRID                1120
#define IDC_EDT_OFFSET_ROT_Z_SPIN       1121
#define IDC_EDT_FILE                    1121
#define IDC_CHK_REACHABLE               1121
#define IDC_EDT_OFFSET_SCL_Z_SPIN       1122
#define IDC_EDT_TILE_X                  1122
#define IDC_EDT_WORLD_Z_SPIN            1122
#define IDC_CHK_SHOWFOOTPRINT           1122
#define IDC_EDT_OFFSET_SCL_Y_SPIN       1123
#define IDC_EDT_TILE_Y                  1123
#define IDC_SPIN_TRANSPORT_X            1123
#define IDC_EDT_OFFSET_SCL_X_SPIN       1124
#define IDC_EDT_OFFSET_SCL_XYZ_SPIN     1124
#define IDC_SPIN_TARGET_X               1124
#define IDC_EDT_LIQUID_TEXTURE          1125
#define IDC_SPIN_TRANSPORT_Y            1125
#define IDC_CHK_ADDWATER                1126
#define IDC_EDT_TRANSPORT_Y_SCALE       1126
#define IDC_SPIN_FLYROUTE_Z             1126
#define IDC_EDIT1                       1127
#define IDC_EDT_TEXTURE                 1127
#define IDC_EDIT_FOG_DEPTH              1127
#define IDC_EDT_SIZE_FROM               1127
#define IDC_EDIT_SIZE                   1127
#define IDC_EDIT_SNAPPATH               1127
#define IDC_EDIT_CLIENTFILE             1127
#define IDC_EDT_LIGHT_NAME              1127
#define IDC_EDT_FOG_NAME                1127
#define IDC_EDIT_ZONE_NAME              1127
#define IDC_EDIT_REACHABLEANGLE         1127
#define IDC_SPIN_TRANSPORT_X_SCALE      1127
#define IDC_EDIT_TEXTURE_X0             1127
#define IDC_EDIT_LIGHTMAP_VALUE         1127
#define IDC_EDIT_SKYBOXPATH             1127
#define IDC_EDIT_STATUSLEVEL            1127
#define IDC_EDIT_NPCNAME                1127
#define IDC_ID                          1127
#define IDC_EDT_SIZE_TO                 1128
#define IDC_EDT_SIZE_TOO                1128
#define IDC_EDIT_MAPSCALE               1128
#define IDC_SPIN_TRANSPORT_Y_SCALE      1128
#define IDC_EDIT_CHINESENAME            1128
#define IDC_EDIT_TEXTURE_Y0             1128
#define IDC_NPC_X                       1128
#define IDC_ACTIONNAME                  1128
#define IDC_EDIT2                       1128
#define IDC_EDIT_SKYBOXPATH2            1128
#define IDC_EDIT_SKYBOXTEXTUREPATH      1128
#define IDC_EDT_ROT_FROM                1129
#define IDC_EDT_SIZE_DENSITY            1129
#define IDC_SPIN_TARGET_Y               1129
#define IDC_EDIT_TEXTURE_SCALEX0        1129
#define IDC_EDIT_MINLEVEL               1129
#define IDC_NPC_Y                       1129
#define IDC_ACTIONPRO                   1129
#define IDC_EDIT3                       1129
#define IDC_EDT_ROT_TO                  1130
#define IDC_EDT_SIZE_FRM                1130
#define IDC_SPIN_TARGET_DIR             1130
#define IDC_EDIT_TEXTURE_SCALEY0        1130
#define IDC_EDIT_TIME                   1130
#define IDC_NPC_Z                       1130
#define IDC_CCDIR                       1130
#define IDC_EDIT4                       1130
#define IDC_EDT_MONSTERQUAD_RELIFE      1130
#define IDC_EDT_NUM_FROM                1131
#define IDC_EDIT_TEXTURE_ROTATION       1131
#define IDC_ED_MapNameColor             1131
#define IDC_NPC_DIR                     1131
#define IDC_BSHOW                       1131
#define IDC_EDIT6                       1131
#define IDC_EDIT_STRINGID               1131
#define IDC_EDT_MONSTERQUAD_AIVALUE     1131
#define IDC_EDT_NUM_TO                  1132
#define IDC_EDIT_MAPCOUNT               1132
#define IDC_NPC_SCALE                   1132
#define IDC_TITLE                       1132
#define IDC_EDIT7                       1132
#define IDC_EDIT_PROBABILITY            1132
#define IDC_EDIT_ARTFONT_TOP            1132
#define IDC_BTN_DARK_AMBIENT            1133
#define IDC_EDIT_UNITCOUNT              1133
#define IDC_POS_X                       1133
#define IDC_HEADPICTURE                 1133
#define IDC_BTN_DARK_DIFFUSE            1134
#define IDC_BTN_DARK_AMBIENT2           1134
#define IDC_BTN_DARK_FOG                1134
#define IDC_EDIT_MINLEVEL3              1134
#define IDC_ED_MapTip                   1134
#define IDC_POS_Y                       1134
#define IDC_POSX                        1134
#define IDC_TITLE2                      1134
#define IDC_BIGMAPSHOW                  1134
#define IDC_BTN_DARK_SPECULAR           1135
#define IDC_LIST_LIGHT_FOG              1135
#define IDC_LIST_LIGHT                  1135
#define IDC_POS_MAPID                   1135
#define IDC_POSZ                        1135
#define IDC_EDIT_ARTFONT_RIGHT          1135
#define IDC_BTN_FOG_COLOR               1136
#define IDC_LIST_FOG                    1136
#define IDC_BTN_LIGHT_AMBIENT           1136
#define IDC_NAME                        1136
#define IDC_EDIT9                       1136
#define IDC_EDIT_ARTFONT_BOTTOM         1136
#define IDC_DATETIMEPICKER1             1137
#define IDC_LIST_ZONE                   1137
#define IDC_LEV                         1137
#define IDC_SLIDER_DAYTIME              1138
#define IDC_BTN_LIGHT_DIFFUSE           1138
#define IDC_MOVEPATH                    1138
#define IDC_CHECK_RECURSION             1139
#define IDC_BTN_LIGHT_SPECULAR          1139
#define IDC_ScriptFile                  1139
#define IDC_EDIT_LIGHT_DIR_X            1140
#define IDC_BCOLLISION                  1140
#define IDC_EDIT_LIGHT_DIR_Y            1141
#define IDC_LIST_DOODADS                1141
#define IDC_NPCTISP                     1141
#define IDC_EDIT_LIGHT_DIR_Z            1142
#define IDC_BTN_LIGHT_DIFFUSE2          1142
#define IDC_BTN_LIGHT_SUNLESS           1142
#define IDC_BODYSCALE                   1142
#define IDC_CHK_RANDOM                  1143
#define IDC_EDIT_LIGHT_DIR_X2           1143
#define IDC_EDIT_DARK_DIR_X             1143
#define IDC_DIRECT                      1143
#define IDC_PINYIN                      1143
#define IDC_EDIT_LIGHT_DIR_Y2           1144
#define IDC_EDIT_DARK_DIR_Y             1144
#define IDC_POSY                        1144
#define IDC_PINYIN2                     1144
#define IDC_ISDYNAMICCOLLISION          1144
#define IDC_EDIT_LIGHT_DIR_Z2           1145
#define IDC_EDIT_DARK_DIR_Z             1145
#define IDC_NPCNAME                     1145
#define IDC_SOUND                       1145
#define IDC_XPOS                        1146
#define IDC_fight_view                  1146
#define IDC_SHOW                        1147
#define IDC_DOD_BRUSH_SIZE1             1148
#define IDC_FINDTARGETID                1148
#define IDC_DOD_BRUSH_SIZE2             1149
#define IDC_YPOS                        1149
#define IDC_DOD_BRUSH_SIZE3             1150
#define IDC_ELAPNEXT                    1150
#define IDC_DOD_BRUSH_SIZE4             1151
#define IDC_TALKPRO                     1151
#define IDC_PARSEID                     1152
#define IDC_ElAPID                      1153
#define IDC_EDT_NEW_TEXTURE             1154
#define IDC_ELAPTIME                    1154
#define IDC_SLIDER_SIZE                 1155
#define IDC_EDIT_SERVERFILE             1156
#define IDC_EDIT_SL_WORLD_Y             1168
#define IDC_EDIT_SL_NEARDIST            1174
#define IDC_LIST_LIGHT_PARAM            1175
#define IDC_BTN_LIGHT_FOG               1176
#define IDC_BTN_LIGHT_DEL               1177
#define IDC_BTN_LIGHT_ADD               1178
#define IDC_BTN_LIGHT_SET               1179
#define IDC_BTN_FOG_ADD                 1180
#define IDC_BTN_FOG_DEL                 1181
#define IDC_BTN_LIGHT_PREVIEW_DARK      1181
#define IDC_BTN_FOG_SET                 1182
#define IDC_BTN_LIGHT_PREVIEW_LIGHT     1182
#define IDC_RADIO_SET_ZONE              1183
#define IDC_RADIO_ZONE_PICK             1184
#define IDC_STATIC_HEIGHT               1185
#define IDC_EDT_BRUSH_RADIUS            1186
#define IDC_EDT_SELECTED_ZONE           1187
#define IDC_BTN_ZONE_DEL                1188
#define IDC_EDT_DARK_NEAR               1189
#define IDC_BTN_ZONE_PREVIEW2           1189
#define IDC_BTN_ZONE_SET                1189
#define IDC_EDT_DARK_FAR                1190
#define IDC_BTN_ZONE_ADD                1190
#define IDC_TILE                        1190
#define IDC_EDT_LIGHT_NEAR              1191
#define IDC_TILENUM                     1191
#define IDC_BTN_ZONE_SAVE               1191
#define IDC_EDT_LIGHT_FAR               1192
#define IDC_SEALEVEL                    1192
#define IDC_EDIT_SEALEVEL               1193
#define IDC_EDIT_SEAL_HEIGHT            1193
#define IDC_EDIT_WATER_HEIGHT           1193
#define IDC_SEALEVEL2                   1194
#define IDC_SEALEVEL3                   1195
#define IDC_EDIT_AlphaCoaf              1196
#define IDC_DELETEDOODADLEVEL           1197
#define IDC_NEWDOODADLEVEL              1198
#define IDC_CURRDOODADLEVEL             1199
#define IDC_UnitSize                    1201
#define IDC_STATIC6                     1204
#define IDC_STATIC_TYPE                 1205
#define IDC_STATIC13                    1206
#define IDC_STATIC_UNITSIZE             1207
#define IDC_COMBO_DOODAD_BRUSH          1208
#define IDC_BTN_VERTEX_COLOR            1210
#define IDC_BTN_WATER_COLOR             1213
#define IDC_SPIN_LONGITUDE              1215
#define IDC_SPIN_LATITUDE               1216
#define IDC_CHECK_TARGET                1217
#define IDC_CHECK_VISIBLE_MONSTER       1217
#define IDC_CHECK_TILE_CULLING          1217
#define IDC_CHECK_MONSTERPOINTSHOW      1218
#define IDC_CHECK_TILE_CULLING2         1218
#define IDC_CHECK_PAINT_SHADOW          1218
#define IDC_CHECK_RELIVE                1218
#define IDC_SLIDER_HEIGHTSCALE          1220
#define IDC_SLIDER_SIZESCALE            1221
#define IDC_STATIC_HEIGHTSCALE          1222
#define IDC_STATIC_SIZESCALE            1223
#define IDC_EDIT_MAPPATH                1223
#define IDC_EDT_TARGET_Y                1224
#define IDC_EDT_TARGET_TILE             1225
#define IDC_CHK_PICKTRANSPORT           1226
#define IDC_EDT_TARGET_DIR              1227
#define IDC_EDT_ROUTE_INDEX             1227
#define IDC_EDT_TARGET_ID               1228
#define IDC_EDT_ROUTE_NAME              1228
#define IDC_EDT_TARGET_INDEX            1229
#define IDC_EDT_MONSTER_RADIO           1229
#define IDC_EDT_NEXT_ROUTE              1229
#define IDC_RADIO_TRANSPORT             1230
#define IDC_EDT_WALK_LENGHT             1230
#define IDC_EDT_WALK_LENGTH             1230
#define IDC_RADIO_TARGET                1231
#define IDC_EDT_MONSTER_INTEVEL         1231
#define IDC_EDT_MONSTER_INTERVAL        1231
#define IDC_EDT_STAY_TIME               1231
#define IDC_EDT_MERGEWTD_UPLEFT         1232
#define IDC_RADIO_PICK_MONSTERQUAD      1232
#define IDC_EDT_STAY_TIME2              1232
#define IDC_EDT_MONSTERQUAD_X           1235
#define IDC_EDT_MONSTERQUAD_Y           1236
#define IDC_RADIO_MONSTERQUAD           1237
#define IDC_EDT_MONSTERQUAD_X_SCALE     1238
#define IDC_EDT_MONSTERQUAD_Y_SCALE     1239
#define IDC_SPIN_MONSTERQUAD_X          1240
#define IDC_SPIN_MONSTERQUAD_Y          1241
#define IDC_SPIN_MONSTERQUAD_X_SCALE    1242
#define IDC_SPIN_MONSTERQUAD_Y_SCALE    1243
#define IDC_EDT_MONSTER_NUMBER          1244
#define IDC_BUTTON_MONSTERPOINTREFRESH  1245
#define IDC_EDT_MONSTER_TYPE3           1246
#define IDC_EDT_SPLITWTD_UPLEFT         1246
#define IDC_EDT_SPLITWTD_DOWNRIGHT      1247
#define IDC_RADIO_UPDOWN_SPLIT          1248
#define IDC_RADIO_LEFTRIGHT_SPLIT       1249
#define IDC_SPIN_TEXTURE_X0             1251
#define IDC_SPIN_TEXTURE_Y0             1252
#define IDC_SPIN_TEXTURE_SCALEX0        1253
#define IDC_SPIN_TEXTURE_SCALEY0        1254
#define IDC_CHECK_ALIGN                 1255
#define IDC_SPIN_TEXTURE_ROTATION       1256
#define IDC_RADIO_Level3                1257
#define IDC_RADIO_Level2                1258
#define IDC_LIGHTMAP_CHUNK              1258
#define IDC_RADIO_Level1                1259
#define IDC_LIGHTMAP_TILE               1259
#define IDC_RADIO_Level6                1260
#define IDC_RADIO_Level0                1260
#define IDC_STATIC_TILE                 1260
#define IDC_STATIC_CHUNK                1261
#define IDC_BUTTON1                     1263
#define IDC_BTN_LOADSKYBOX              1263
#define IDC_BUTTON_ADD                  1263
#define IDC_BUTTON_WORLDATTR            1263
#define IDC_BUTFIND                     1263
#define IDC_QUERYFILE                   1263
#define IDC_EDT_MUSIC                   1264
#define IDC_BUTTON_DELETE               1264
#define IDC_BUTTON_DEL                  1264
#define IDC_ADDPP                       1264
#define IDC_STRINGADD                   1264
#define IDC_BUTTON_ADD_TALK             1264
#define IDC_EDT_SELECTED_ENV            1265
#define IDC_BUTTON3                     1265
#define IDC_BUTTON_MODIFIY              1265
#define IDC_DELPP                       1265
#define IDC_STRINGSAVE                  1265
#define IDC_BUTTON_DEL_AUTOTALK         1265
#define IDC_BUTTON_ADD2                 1265
#define IDC_BUTTON_GenerateClosedRoute  1265
#define IDC_LIST_ENV                    1266
#define IDC_ELAPUPDATE                  1266
#define IDC_STRINGDEL                   1266
#define IDC_BUTTON_ADD_TALK2            1266
#define IDC_BUTTON_TALK_CHANGE          1266
#define IDC_EDIT_ENV_NAME               1267
#define IDC_ELAPINSERT                  1267
#define IDC_BTN_ENV_SET                 1268
#define IDC_ACTIONUPDATE                1268
#define IDC_BUTTON_DEL_TALK             1268
#define IDC_BTN_ENV_ADD                 1269
#define IDC_ACTIONINSERT                1269
#define IDC_BTN_ENV_DEL                 1270
#define IDC_TALKUPDATE                  1270
#define IDC_RADIO_SET_ENV               1271
#define IDC_BUTTON9                     1271
#define IDC_TALKINSERT                  1271
#define IDC_BUTTON_Set                  1271
#define IDC_BUTTON_SETMESH              1271
#define IDC_EDT_BRUSH_RADIUS_ENV        1272
#define IDC_NPCFINDUPDATE               1272
#define IDC_RADIO_ENV_PICK              1273
#define IDC_NPCFINDDEL                  1273
#define IDC_NPCFINDINSERT               1274
#define IDC_EDT_NEXT_MAP                1275
#define IDC_FILTER                      1275
#define IDC_NPCMODIFY                   1275
#define IDC_EDT_FLYROUTE_X              1276
#define IDC_RECOVERY                    1276
#define IDC_                            1276
#define IDC_Btn_Fight_Update            1276
#define IDC_EDT_FLYROUTE_Y              1277
#define IDC_NPCUPDATE                   1277
#define IDC_SPIN_FLYROUTE_X             1278
#define IDC_INSERT                      1278
#define IDC_SPIN_FLYROUTE_Y             1279
#define IDC_NPCDEL                      1279
#define IDC_CHK_PICKFLYROUTE            1280
#define IDC_EDT_WALK_SPEED              1281
#define IDC_RADIO_NPC                   1282
#define IDC_RADIO_FLY                   1283
#define IDC_EDT_CLICK2ADD_INDEX         1284
#define IDC_EDT_CLICK2ADD_NAME          1285
#define IDC_EDT_CLICK2ADD_X             1286
#define IDC_EDT_CLICK2ADD_Y             1287
#define IDC_EDT_CLICK2ADD_Z             1288
#define IDC_CHK_PICKCLICK2ADD           1289
#define IDC_LIST_CLICK2ADD              1290
#define IDC_SPIN_CLICK2ADD_Z            1291
#define IDC_SPIN_CLICK2ADD_Y            1292
#define IDC_SPIN_CLICK2ADD_X            1293
#define IDC_RADIO_SOUNDPOINT            1294
#define IDC_RADIO_ADDNPC                1295
#define IDC_BUTTON_DELETE_CLICK2ADD     1296
#define IDC_EDT_SOUNDPOINT              1297
#define IDC_EDT_CLICK2ADD_Value1        1300
#define IDC_SPIN_CLICK2ADD_Value1       1301
#define IDC_CHECK_RIDE                  1301
#define IDC_CHECK_SHOWFOOT              1302
#define IDC_RADIO_ISTARGET              1302
#define IDC_RADIO_ISRELIVE              1303
#define IDC_CHECK_SHOWFOOT2             1303
#define IDC_CHECK_CANPK                 1303
#define IDC_CHECK_REDNAME               1305
#define IDC_CANCEL                      1307
#define IDC_SAVEDATA                    1307
#define IDC_CHECK_SYSTEMCREATE          1308
#define IDC_SAVEPOS                     1308
#define IDC_STATIC_REGIONOFFSETX        1309
#define IDC_STATIC_REGIONOFFSETY        1310
#define IDC_STATIC_REGIONEDGE           1311
#define IDC_EDIT_REGIONOFFSETX          1312
#define IDC_EDIT_REGIONOFFSETY          1313
#define IDC_EDIT_REGION_EDGE            1314
#define IDC_COMBO_CANPK                 1315
#define IDC_STATIC_MAPTIPSTRING         1316
#define IDC_COMBO_POS_TYPE              1318
#define IDC_COMBO_POS_NPCID             1319
#define IDC_COMMTYPE                    1319
#define IDC_COMBO_SHOW                  1319
#define IDC_COMMODEL                    1320
#define IDC_COMBO_MODID                 1320
#define IDC_RADIO_NPC_EDIT              1321
#define IDC_COMFINDTYPE                 1321
#define IDC_RADIO_ADD_POS               1322
#define IDC_COMBOFINDMAPID              1322
#define IDC_RADIO_PICKEDIT              1323
#define IDC_COMNPCSTR                   1323
#define IDC_RADIO_ADD_NPC               1324
#define IDC_COMMAP                      1325
#define IDC_RADIO_NONE                  1325
#define IDC_MAXNPCINFO                  1326
#define IDC_STANOTE                     1327
#define IDC_MAXNPCINFO2                 1328
#define IDC_LOADSTRING                  1328
#define IDC_STRINGID                    1329
#define IDC_STRING                      1330
#define IDC_TREESTRINGID                1331
#define IDC_BUTTON2                     1332
#define IDC_BUTUPDAEPOS                 1332
#define IDC_DEL_NPCMENU                 1332
#define IDC_BUTUPDATESTR                1333
#define IDC_BUTDELPOI                   1334
#define IDC_BUTUPPOI                    1335
#define IDC_UPDATENPC                   1336
#define IDC_CHECK1                      1337
#define IDC_SHOWLINE                    1337
#define IDC_CHECK_LIGHTMAP_CASTSHADOW   1337
#define IDC_CHECK_NEED                  1337
#define IDC_CHECK_CPY_MONSTER           1337
#define IDC_COPYNPC                     1338
#define IDC_DELNPC                      1340
#define IDC_TEXTMAP                     1341
#define IDC_NPCMENU_STRINGID            1341
#define IDC_EDIT5                       1342
#define IDC_NPCMENU_CONTENT             1342
#define IDC_ACTIONSCRIPT                1342
#define IDC_EDIT_SCRIPTFILE             1342
#define IDC_EDT_MONSTERQUAD_DIR         1342
#define IDC_NPCMENU_UPDATE              1343
#define IDC_RADIO_AMBIENT               1344
#define IDC_SAVE_STRING                 1344
#define IDC_RADIO2                      1345
#define IDC_RADIO_DIFFUSE               1345
#define IDC_RADIO3                      1346
#define IDC_RADIO_SPECULAR              1346
#define IDC_RADIO4                      1347
#define IDC_RADIO_SUNLESS               1347
#define IDC_SLIDER1                     1348
#define IDC_SLIDER_COLOR_H              1348
#define IDC_SLIDER_MESHHEIGHT           1348
#define IDC_SLIDER_CONTRAST_R           1348
#define IDC_SLIDER_SL_H                 1348
#define IDC_SLIDER_BLOOMSCALE           1348
#define IDC_SLIDER_ALPHA                1348
#define IDC_SLIDER2                     1349
#define IDC_SLIDER_COLOR_S              1349
#define IDC_BUTTON_ADD_AUTOTALK         1349
#define IDC_SLIDER_CONTRAST_G           1349
#define IDC_SLIDER_SL_S                 1349
#define IDC_SLIDER_BLOOMLUMNIANCE       1349
#define IDC_SLIDER3                     1350
#define IDC_SLIDER_COLOR_L              1350
#define IDC_BUTTON_AUTOTALK_CHANGE      1350
#define IDC_SLIDER_CONTRAST_B           1350
#define IDC_SLIDER_SL_L                 1350
#define IDC_EDIT_BLOOMSCALE             1351
#define IDC_EDIT_TIMES                  1351
#define IDC_SLIDER_CONTRAST_C           1351
#define IDC_EDIT_LUMINANCE              1352
#define IDC_EDIT_ID                     1352
#define IDC_EDIT_NEXTTIMEID             1353
#define IDC_BUTTON_SELTEXTURE           1354
#define IDC_EDIT_ARTFONT_LEFT           1355
#define IDC_STATIC_ObjectList           1356
#define IDC_EDIT_Result                 1357
#define IDC_EDIT_x                      1358
#define IDC_EDIT_y                      1359
#define IDC_PROGRESS_LIGHTMAP_MESH      1360
#define IDC_STATIC_LM_MESH              1361
#define IDC_BTN_LIGHTMAP_ONEMODEL       1362
#define IDC_BUTTON_CONTRAST             1363
#define IDC_BUTTON_RESET                1364
#define IDC_BUTTON_BLOOM                1364
#define IDC_LIST_STATIC_LIGHT           1365
#define IDC_TREE2                       1365
#define IDC_EDIT_SL_WORLD_X             1366
#define IDC_BNACTION_ADD                1366
#define IDC_SPIN_SL_WORLD_X             1367
#define IDC_BNACTION_DELETE             1367
#define IDC_EDIT_R_MIN                  1368
#define IDC_SPIN_SL_WORLD_Y             1369
#define IDC_EDIT_R_MAX                  1369
#define IDC_EDIT_SL_WORLD_Z             1370
#define IDC_SPIN_SL_WORLD_Z             1371
#define IDC_EDIT_R_SEX                  1371
#define IDC_EDIT_SL_DISTANCE            1372
#define IDC_EDIT_R_TASKID               1372
#define IDC_SPIN_SL_DISTANCE            1373
#define IDC_BNREQUIRE_MODIFY            1373
#define IDC_BNREQUIRE_INSERT            1374
#define IDC_SPIN_SL_NEARDIST            1375
#define IDC_BNEVENT_MODIFY              1375
#define IDC_BTN_SL_COLOR                1376
#define IDC_BNEVENT_INSERT              1376
#define IDC_BUTTON_SL_DELETE            1377
#define IDC_EDIT_E_VALUE                1377
#define IDC_BUTTON_MOVETO_LIGHT         1378
#define IDC_EDIT_PROB                   1378
#define IDC_EDIT_E_PROB                 1378
#define IDC_BUTTON_BLOOMRESET           1379
#define IDC_EDIT_E_DELAYTIME            1379
#define IDC_STATIC_VALUE                1380
#define IDC_SPIN_Fight_view             1381
#define IDC_NPCType                     1381
#define IDC_COMBONPCType                1382
#define IDC_COMBO_MONSTER               1383
#define IDC_CHECK_ISONE_POINT           1384
#define IDC_SPIN_ONEPOINT_DIR           1385
#define IDC_EDIT_ONEPOINT_DIR           1386
#define IDC_STATIC_SIGHT_LENTH          1387
#define IDC_STATIC_WATER_ALPHA          1388
#define IDC_BTN_DEL_CHUNK_LIQUID        1389
#define IDC_CHECK2                      1390
#define IDC_CK_USE_WINTAB_4_ALPHA       1390
#define IDC_EDT_MONSTERQUAD_NUM         1391
#define IDC_EDT_MONSTERQUAD_DEADSCRIPT  1392
#define IDC_EDT_MONSTERQUAD_AISCRIPT    1393
#define IDC_CAMERA_FOLLOW_MEX           1394
#define IDC_EDT_MONSTERQUAD_COUNTY      1394
#define IDC_EDT_MONSTERQUAD_ZONE_NAME   1395
#define IDC_SPIN_CLICK2ADD_Value0       1397
#define IDC_EDT_MONSTERQUAD_AISTEP      1500
#define IDC_COMBO_MONSTERQUAD_PK        1501
#define IDC_COMBO_MONSTERQUAD_Stall     1502
#define IDC_COMBO_MONSTERQUAD_Stall2    1503
#define IDC_EDT_STAY_ACTION             1527
#define IDC_EDT_TARGET_INDEX2           1528
#define IDC_EDT_TARGET_MAPID            1529
#define IDC_RADIO_UPDOWN                1530
#define IDC_EDT_ENTERSCRIPT             1530
#define IDC_EDT_MONSTER_TYPE1           1531
#define IDC_EDT_LEAVESCRIPT             1531
#define IDC_RADIO_LEFTRIGHT             1532
#define IDC_EDT_CHANGE_MODEL_PATH       1533
#define IDC_EDT_MONSTER_TYPE2           1534
#define IDC_EDT_CLICK2ADD_Value0        1601
#define IDB_MAP_MODELS_DEL              1602
#define IDB_MAP_MODEL_CLEAN_UNUSED      1603
#define IDC_CHECK_SUNLIGHTENBLE         2000
#define IDR_PANE_PROPERTIES             4001
#define IDR_PANE_WORLD_EXPLORER         4002
#define IDR_PANE_WORLD_HISTORY          4003
#define IDR_PANE_WORLD_PREVIEW          4004
#define IDR_PANE_WORLD_TOOLS            4005
#define ID_32771                        32771
#define ID_CAMERA_CREATE                32772
#define ID_32773                        32773
#define ID_VIEW_CAMERALIST              32774
#define ID_EDIT_REDO32775               32775
#define ID_FILE_NEWTILE                 32778
#define ID_FILE_OPENTILE                32779
#define ID_WORLD_ADD                    32781
#define IDS_STRING32782                 32782
#define ID_WORLD_DEL                    32786
#define ID_TOOLBAR_WORLD_NEW            32787
#define ID_TOOLBAR_WORLD_ADD            32788
#define ID_TOOLBAR_WORLD_DEL            32789
#define ID_BUTTON32792                  32792
#define ID_BTN_UNDO                     32792
#define ID_BTN_REDO                     32793
#define ID_BTN_FACE                     32794
#define ID_BTN_VERTEX                   32795
#define ID_BTN_OBJECT                   32796
#define ID_BTN_DISPLAY_FACE             32798
#define ID_BTN_DISPLAY_VERT             32799
#define ID_BTN_DISPLAY_TEXTURE          32800
#define ID_BTN_SHADOW                   32801
#define ID_BTN_DISPLAY_SHADOW           32802
#define ID_BTN_SHOW_BOUND               32803
#define ID_BTN_SELECT                   32804
#define ID_BTN_SELECT_EX                32805
#define ID_BTN_SELECT_GROUP             32806
#define ID_BTN_PROPERTY                 32807
#define ID_BTN_EDIT_MOVE                32808
#define ID_BTN_EDIT_ROTATE              32809
#define ID_BTN_EDIT_SCALE               32810
#define ID_BUTTON32812                  32812
#define ID_BTN_SELECT_NAME              32812
#define ID_BUTTON32814                  32814
#define ID_BTN_SELECT_NAME_EX           32814
#define ID_BTN_DISPLAY_BOUNDBOX         32816
#define ID_BTN_DISPLAY_NORMAL           32817
#define ID_BTN_DISPLAY_CHUNK            32818
#define ID_BTN_SELECT_FILTER            32819
#define ID_BTN_SELECT_NAME_GROUP        32820
#define ID_BTN_SELECT_FILTER_EX         32821
#define ID_BTN_EDIT_OBJECT              32822
#define ID_BTN_EDIT_VERT                32823
#define ID_BUTTON32824                  32824
#define ID_BTN_EDIT_CAMERA              32824
#define ID_BTN_DISPLAY_GRID             32825
#define ID_BTN_BRUSH_SIZE_1             32826
#define ID_BUTTON32827                  32827
#define ID_BTN_BRUSH_SIZE_3             32828
#define ID_BTN_BRUSH_SIZE_4             32829
#define ID_BTN_BRUSH_SIZE_0             32830
#define ID_BTN_BRUSH_SIZE_2             32831
#define ID_BTN_BRUSH_ADD                32832
#define ID_BTN_BRUSH_SUB                32833
#define ID_BUTTON32834                  32834
#define ID_FILE_SAVEAS                  32835
#define ID_BTN_VERTEX_HEIGHT            32836
#define ID_BTN_PAINT_SHADOW             32838
#define ID_BTN_PAINTTEXTURE             32839
#define ID_BTN_LAYEREDIT                32840
#define ID_BTN_PUTOBJECT                32841
#define ID_BTN_TB_EDITOBJECT            32842
#define ID_BTN_FILLLIQUID               32843
#define ID_BUTTON32844                  32844
#define ID_BTN_EDITLIQUID               32844
#define ID_32845                        32845
#define ID_32846                        32846
#define ID_VIEW_MAP                     32847
#define ID_VIEW_TOOLS                   32848
#define ID_TOOLS_CREATE                 32851
#define ID_TOOLS_MODIFY                 32852
#define ID_TOOLS_TERRAIN                32853
#define ID_TOOLS_LAYER                  32854
#define ID_TOOLS_DOODAD                 32855
#define ID_TOOLS_MODLE                  32856
#define ID_TOOLS_LIQUID                 32857
#define ID_TOOLS_SCENE                  32858
#define ID_TOOLS_ENV                    32859
#define ID_BTN_PAINT_NORMAL             32860
#define ID_BTN_LOCK_VERT                32862
#define ID_TOOLBAR_SECNE_WORLD          32863
#define ID_TOOLBAR_SECNE_ENV            32864
#define ID_TOOLBAR_SCENE_LIGHT          32865
#define ID_TOOLBAR_SCENE_FOG            32866
#define ID_TOOLBAR_SCENE_ZONE           32867
#define ID_POP_DELETE                   32868
#define ID_POP_32867                    32869
#define ID_POP_PROPERTY                 32870
#define ID_LIST_POP_ADD                 32871
#define ID_LIST_POP_DELETE              32872
#define ID_LIST_POP_PROPERTY            32873
#define ID_POP_32872                    32874
#define ID_LIST_POP_ACTIVE              32875
#define ID_BTN_DISPLAYLIQUID            32876
#define ID_POP_32875                    32877
#define ID_POP_TILE_SNAP                32878
#define ID_POP_32877                    32879
#define ID_POP_TILE_REPLACETEXTURE      32880
#define ID_BTN_DISPLAYMODEL             32881
#define ID_SERVER_MAP                   32882
#define ID_FILE_EXPORTSERVERMAP         32883
#define ID_BTN_ZONE                     32892
#define ID_BTN_DISPLAY_ENV              32893
#define ID_POP_32894                    32894
#define ID_POP_TILE_CLEAN_MODEL         32895
#define ID_Animation                    32898
#define ID_BTN_DISPLAYDOODAD            32899
#define ID_BTN_EDIT_GAME_CAMERA         32901
#define ID_POP_32902                    32902
#define ID_POP_REACHABLEMAP             32903
#define ID_TOOLS_TRANSPORT              32905
#define ID_POP_32906                    32906
#define ID_POP_TRANSPORT                32907
#define ID_FILE_EXPORTGAMEMAP           32908
#define ID_POP_CONVERT2GAMEMAP          32909
#define ID_FILE_MERGETILE               32910
#define ID_BUTTON_LOD                   32913
#define ID_TOOLS_MONSTER                32914
#define ID_POP_32915                    32915
#define ID_POP_MonsterData              32916
#define ID_BUTTON_Monster               32918
#define ID_FILE_32919                   32919
#define ID_FILE_SPLITTILE               32920
#define ID_BUTTON_LIGHTMAP              32921
#define ID_BUTTON32923                  32923
#define ID_BUTTON_LIGHTMAP_SETTING      32924
#define ID_POP_32925                    32925
#define ID_POP_CAL_PF_WEIGHT            32926
#define ID_BUTTON32929                  32929
#define ID_BTN_DISPLAY_ZONE             32929
#define ID_BUTTON_TERRAIN_LAYER         32932
#define ID_TOOLS_FLYROUTE               32935
#define ID_TOOLS_CLICK2ADD              32936
#define ID_POP_32937                    32937
#define ID_POP_WATER_MAP                32938
#define ID_POP_32939                    32939
#define ID_POP_BBOX_SNAP                32940
#define ID_BUTTON_LOADSKYBOX            32941
#define ID_TOOLS_NPC                    32942
#define ID_32943                        32943
#define ID_32944                        32944
#define ID_32945                        32945
#define ID_BUTTON_MULTISEL              32949
#define ID_ACCELERATOR32949             32949
#define ID_BUTTON32950                  32950
#define ID_BUTTON_MULTISELTEXTURE       32950
#define ID_BUTTON_FREEBLOCK             32957
#define ID_BUTTON_SlopeCheck            32958
#define ID_BUTTON_ColiCheck             32959
#define ID_32960                        32960
#define ID_OPERATION_Locate             32961
#define ID_EDIT_COPY32964               32964
#define ID_POP_32966                    32966
#define ID_POP_32967                    32967
#define ID_POP_32968                    32968
#define ID_POP_model_move               32969
#define ID_POP_model_rotate             32970
#define ID_POP_model_scale              32971
#define ID_POP_32960                    32972
#define ID_BUTTON_MESH_LIGHTMAP         32973
#define ID_VIEW_DEBUGMSG                32974
#define ID_USE_DYNAMICLIGHT             32975
#define ID_VIEW_USEDYNAMICLIGHT         32976
#define ID_TOOLS_STATICLIGHT            32977
#define ID_BUTTON32978                  32978
#define ID_BTN_CHASCAMERA               32979
#define ID_BTN_CHASECAMERA              32979
#define ID_32980                        32980
#define IDM_RELEASE_LOG                 32981
#define ID_BUTTON_RENDER_MINIMAP        32982
#define ID_BUTTON32985                  32985
#define ID_BUTTON_SHOW_AABB             32985
#define ID_POP_32986                    32986
#define IDM_MAP_MODELS                  32987
#define ID_BUTTON_SHOW_FOG              32988
#define ID_TerrainBump                  32989
#define ID_BUTTON32990                  32990
#define ID_SAVESHMP                     32990
#define ID_STATUS_PROMPT                39136
#define ID_STATUS_MOUSEPOS              39137
#define ID_STATUS_WORLDPOS              39138
#define ID_STATUS_COUNT                 39139
#define ID_INDICATOR_PROG               39140
#define ID_POP_HEIGHT_MAP               39141
#define ID_NPCMENU_INSERT               39142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         32991
#define _APS_NEXT_CONTROL_VALUE         1396
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
