#pragma once

// C Header Files
#include <signal.h>
#include <assert.h>
#include <tchar.h>
#include <stdio.h>
#include <direct.h>
#include <time.h>
#include <stdarg.h>
#include <math.h>
#include <shlwapi.h>
#include <io.h>
#include <errno.h>
#include <conio.h>
#include <memory.h>
#include <malloc.h>
#include <fcntl.h>

// C++ Stream stuff
#include <fstream>
#include <iostream>
#include <iomanip>
#include <sstream>
#include <cstdlib>
#include <utility>
#include <ctime>

// STL containers
#include <vector>
#include <map>
#include <hash_map>
#include <hash_set>
#include <string>
#include <set>
#include <list>
#include <deque>
#include <stack>
#include <queue>
#include <algorithm>

// windows
#define WIN32_LEAN_AND_MEAN		// Exclude rarely-used stuff from Windows headers
#include <windows.h>
#include <time.h>

//////////////////////////////////////////////////////////////////////////
// disable warning 

// Turn off warnings generated by long std templates
// This warns about truncation to 255 characters in debug/browse info
#pragma warning (disable : 4786)

// disable: "conversion from 'double' to 'float', possible loss of data
#pragma warning (disable : 4244)

// disable: "truncation from 'double' to 'float'
#pragma warning (disable : 4305)

// unreferenced formal parameter
#pragma warning (disable : 4100)

// disable: "<type> needs to have dll-interface to be used by clients'
// Happens on STL member variables which are not public therefore is ok
#pragma warning (disable : 4251)

// conversion from 'size_t' to 'int', possible loss of data
#pragma warning (disable : 4267)

// conversion from '__w64 int' to 'unsigned long', possible loss of data
#pragma warning (disable : 4244)

// disable: "non dll-interface class used as base for dll-interface class"
#pragma warning (disable : 4275)

// disable: '<' : signed/unsigned mismatch
#pragma warning (disable : 4018)

// disable: 'std::hash_map<_Kty,_Ty>' was declared deprecated
#pragma warning (disable : 4996)

// disable: 'BOOL' : forcing value to bool 'true' or 'false'
#pragma warning (disable : 4800)

// disable: conditional expression is constant
#pragma warning (disable : 4127)